### ISSUE TITLE
[deno][react-dom/server] error: Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by harleylang** [pikapkg/cdn#127]
Further to #120, I'm attempting to use:

```
{
    "imports": {
        "react-dom/server": "https://cdn.skypack.dev/react-dom/server?dts",
    }
}
```

The error I am receiving:

```
error: Uncaught ReferenceError: process is not defined
  if (process.env.NODE_ENV !== "production") {
  ^
    at https://cdn.skypack.dev/-/react-dom@v17.0.1-DtIXT56q6U8PbgLMrBhE/dist=es2020,mode=imports/unoptimized/cjs/react-dom-server.node.development.js:17:3
    at createCommonjsModule (https://cdn.skypack.dev/-/react-dom@v17.0.1-DtIXT56q6U8PbgLMrBhE/dist=es2020,mode=imports/unoptimized/cjs/react-dom-server.node.development.js:6:10)
    at https://cdn.skypack.dev/-/react-dom@v17.0.1-DtIXT56q6U8PbgLMrBhE/dist=es2020,mode=imports/unoptimized/cjs/react-dom-server.node.development.js:16:22
```

Full mwe here: https://github.com/harleylang/deno-react-mwe

**Comment by drwpow** [comment]
Just out of curiosity, can you try loading `react-dom/server.browser` instead? That may be more Deno-friendly with less Node.js code.

**Comment by harleylang** [comment]
Sure thing! Just tested this with my `import_map.json` file:

```
{
    "imports": {
        "react": "https://cdn.skypack.dev/react?dts",
        "react-dom": "https://cdn.skypack.dev/react-dom?dts",
        "react-dom/server": "https://cdn.skypack.dev/react-dom/server.browser?dts",
        "serve": "https://deno.land/std@0.85.0/http/server.ts"
    }
}
```

Ran `deno run --reload --unstable --import-map=import_map.json --allow-net ./src/Server.tsx` (same repo as mentioned in OP) and this error occurred:

```
...
Download https://cdn.skypack.dev/-/react-dom@v17.0.1-DtIXT56q6U8PbgLMrBhE/dist=es2020,mode=imports/unoptimized/cjs/react-dom-server.browser.production.min.js
Check file:///home/harley/Development/deno-react-mwe/src/Server.tsx
error: Error: Unable to resolve media type for specifier: "https://cdn.skypack.dev/-/react-dom@v17.0.1-DtIXT56q6U8PbgLMrBhE/dist=es2020,mode=types/server.browser"
    at processResponse (deno:core/core.js:212:11)
    at Object.jsonOpSync (deno:core/core.js:235:12)
    at Object.resolveModuleNames (deno:cli/tsc/99_main_compiler.js:318:29)
    at actualResolveModuleNamesWorker (deno:cli/tsc/00_typescript.js:105299:133)
    at resolveModuleNamesWorker (deno:cli/tsc/00_typescript.js:105537:26)
    at resolveModuleNamesReusingOldState (deno:cli/tsc/00_typescript.js:105651:24)
    at processImportedModules (deno:cli/tsc/00_typescript.js:107138:35)
    at findSourceFileWorker (deno:cli/tsc/00_typescript.js:106910:17)
    at findSourceFile (deno:cli/tsc/00_typescript.js:106772:26)
    at deno:cli/tsc/00_typescript.js:106729:85
```

**Comment by ynwd** [comment]
Same here

**Comment by matthewp** [comment]
Does anyone have a test Deno project they can provide? We've made some changes in our staging environment that *should* fix the `process` error, but very likely there are other issues. I'd like to try though.

**Comment by harleylang** [comment]
Hey @matthewp try out my repo here: https://github.com/harleylang/deno-react-mwe

Command to run after clone: `deno run --reload --unstable --import-map=import_map.json --allow-net ./src/Server.tsx`

**Comment by jaydenseric** [comment]
A similar runtime error happens anytime you use Deno to import a module that uses the new JSX runtime:

https://cdn.skypack.dev/react-waterfall-render@v2.0.0/public/waterfallRender.js

```
error: Uncaught ReferenceError: process is not defined
  if (process.env.NODE_ENV !== "production") {
  ^
    at https://cdn.skypack.dev/-/react@v17.0.1-yH0aYV1FOvoIPeKBbHxg/dist=es2020,mode=imports/unoptimized/cjs/react-jsx-runtime.development.js:16:3
    at createCommonjsModule (https://cdn.skypack.dev/-/react@v17.0.1-yH0aYV1FOvoIPeKBbHxg/dist=es2020,mode=imports/unoptimized/cjs/react-jsx-runtime.development.js:5:10)
    at https://cdn.skypack.dev/-/react@v17.0.1-yH0aYV1FOvoIPeKBbHxg/dist=es2020,mode=imports/unoptimized/cjs/react-jsx-runtime.development.js:15:22
```

- https://github.com/jaydenseric/react-waterfall-render/blob/cd46c5599092c00833ea127ab6c13e0f45762aac/public/waterfallRender.js#L3
- https://unpkg.com/react@17.0.2/jsx-runtime.js

Because the import happens in third party code being imported, in our projects it's not an option to change the JSX runtime import path to point to this file to skip the problematic `if (process.env.NODE_ENV === 'production')`:

https://unpkg.com/react@17.0.2/cjs/react-jsx-runtime.production.min.js

This is not a problem in esm.sh, as they provide the `process.env.NODE_ENV` global at build:

- https://github.com/postui/esm.sh/blob/b11caf36f5359079ac20fe30550b2f96b25c8896/server/build.go#L115
- https://github.com/postui/esm.sh/blob/b11caf36f5359079ac20fe30550b2f96b25c8896/server/build.go#L452-L455

Can Skypack do the same?

**Comment by jaydenseric** [comment]
This issue needs to be fixed, but I think this seems to work for using `react-dom/server` in Deno:

```js
import { renderToStaticMarkup } from "https://cdn.skypack.dev/react-dom@17.0.2/cjs/react-dom-server.browser.production.min.js";
```

**Comment by tv42** [comment]
These both work:

```
import ReactDOMServer from "https://cdn.skypack.dev/react-dom@17.0.2/cjs/react-dom-server.browser.production.min.js";
import { renderToString } from "https://cdn.skypack.dev/react-dom@17.0.2/cjs/react-dom-server.browser.production.min.js";
```

but that just lets you hit the next hurdle:

```
error: Uncaught ReferenceError: process is not defined
var warning = process.env.NODE_ENV !== "production" ? function(condition, format) {
              ^
    at https://cdn.skypack.dev/-/fbjs@v3.0.0-ZbTFjfXCBK4oM4pxmPEZ/dist=es2020,mode=imports/unoptimized/lib/warning.js:18:15
```

**Comment by tv42** [comment]
Deno 1.15.1 with `--unstable --compat` might fix this too. This works:

```
deno repl --unstable --compat --eval 'import ReactDOMServer from "https://cdn.skypack.dev/react-dom/server?dts"'
```
