### ISSUE TITLE
ethereumjs-util:  Uncaught TypeError: that.write is not a function

### ISSUE THREAD

**Issue by v1rtl** [pikapkg/cdn#224]
```ts
import * as vm from 'https://cdn.skypack.dev/ethereumjs-util'
```

```
Download https://cdn.skypack.dev/ethereumjs-util
error: Uncaught TypeError: that.write is not a function
  var actual = that.write(string, encoding);
                    ^
    at fromString (https://cdn.skypack.dev/-/ethereumjs-util@v7.1.1-dzXT1JRYIPLeVEmB9GS5/dist=es2020,mode=imports/optimized/ethereumjs-util.js:296:21)
    at from (https://cdn.skypack.dev/-/ethereumjs-util@v7.1.1-dzXT1JRYIPLeVEmB9GS5/dist=es2020,mode=imports/optimized/ethereumjs-util.js:240:12)
    at Function.Buffer.from (https://cdn.skypack.dev/-/ethereumjs-util@v7.1.1-dzXT1JRYIPLeVEmB9GS5/dist=es2020,mode=imports/optimized/ethereumjs-util.js:245:10)
    at https://cdn.skypack.dev/-/ethereumjs-util@v7.1.1-dzXT1JRYIPLeVEmB9GS5/dist=es2020,mode=imports/optimized/ethereumjs-util.js:1638:36
    at createCommonjsModule (https://cdn.skypack.dev/-/ethereumjs-util@v7.1.1-dzXT1JRYIPLeVEmB9GS5/dist=es2020,mode=imports/optimized/ethereumjs-util.js:18:6)
    at https://cdn.skypack.dev/-/ethereumjs-util@v7.1.1-dzXT1JRYIPLeVEmB9GS5/dist=es2020,mode=imports/optimized/ethereumjs-util.js:1627:17
```

**Comment by v1rtl** [comment]
While import of `ethereumjs-util` fails

```
Uncaught TypeError: Module not found "https://deno.land/std/node/string_decoder.ts".
    at https://cdn.skypack.dev/-/keccak@v3.0.1-YgA9EPZQt0hv8smn1fM6/dist=es2019,mode=imports/optimized/keccak.js:1:29
    at async <anonymous>:1:33
```

`@ethereumjs/util` has no problem with being imported
