### ISSUE TITLE
Package @ngneat/elf does not run since it depends on rxjs 

### ISSUE THREAD

**Issue by bjesuiter** [pikapkg/cdn#279]
I can use the following import 
```ts
export * from "https://cdn.skypack.dev/@ngneat/elf@1.5.4?dts";
export * from "https://cdn.skypack.dev/@ngneat/elf-persist-state@1.1.1?dts"; 
```

However, when I try to use the elf store as described here: https://ngneat.github.io/elf/docs/store, 
I get the following runtime errors: 

```cli
Check file:///Users/bjesuiter/Develop/bjesuiter/hu-course-scraper/main.ts
error: TS2614 [ERROR]: Module '"https://cdn.skypack.dev/error/unknown:rxjs?from=@ngneat/elf.js"' has no exported member 'BehaviorSubject'. Did you mean to use 'import BehaviorSubject from "https://cdn.skypack.dev/error/unknown:rxjs?from=@ngneat/elf.js"' instead?
import { BehaviorSubject, Observable } from '/error/unknown:rxjs?from=@ngneat/elf';
         ~~~~~~~~~~~~~~~
    at https://cdn.skypack.dev/-/@ngneat/elf@v1.5.4-IR9D7yzwI1rfw1pX4eYX/dist=es2019,mode=types/lib/store.d.ts:1:10

TS2614 [ERROR]: Module '"https://cdn.skypack.dev/error/unknown:rxjs?from=@ngneat/elf.js"' has no exported member 'Observable'. Did you mean to use 'import Observable from "https://cdn.skypack.dev/error/unknown:rxjs?from=@ngneat/elf.js"' instead?
import { BehaviorSubject, Observable } from '/error/unknown:rxjs?from=@ngneat/elf';
                          ~~~~~~~~~~
    at https://cdn.skypack.dev/-/@ngneat/elf@v1.5.4-IR9D7yzwI1rfw1pX4eYX/dist=es2019,mode=types/lib/store.d.ts:1:27

TS2614 [ERROR]: Module '"https://cdn.skypack.dev/error/unknown:rxjs?from=@ngneat/elf.js"' has no exported member 'MonoTypeOperatorFunction'. Did you mean to use 'import MonoTypeOperatorFunction from "https://cdn.skypack.dev/error/unknown:rxjs?from=@ngneat/elf.js"' instead?
import { MonoTypeOperatorFunction, OperatorFunction } from '/error/unknown:rxjs?from=@ngneat/elf';
         ~~~~~~~~~~~~~~~~~~~~~~~~
    at https://cdn.skypack.dev/-/@ngneat/elf@v1.5.4-IR9D7yzwI1rfw1pX4eYX/dist=es2019,mode=types/lib/operators.d.ts:1:10

TS2614 [ERROR]: Module '"https://cdn.skypack.dev/error/unknown:rxjs?from=@ngneat/elf.js"' has no exported member 'OperatorFunction'. Did you mean to use 'import OperatorFunction from "https://cdn.skypack.dev/error/unknown:rxjs?from=@ngneat/elf.js"' instead?
import { MonoTypeOperatorFunction, OperatorFunction } from '/error/unknown:rxjs?from=@ngneat/elf';
                                   ~~~~~~~~~~~~~~~~
    at https://cdn.skypack.dev/-/@ngneat/elf@v1.5.4-IR9D7yzwI1rfw1pX4eYX/dist=es2019,mode=types/lib/operators.d.ts:1:36

TS2694 [ERROR]: Namespace '"https://cdn.skypack.dev/error/unknown:rxjs?from=@ngneat/elf.js"' has no exported member 'OperatorFunction'.
    at https://cdn.skypack.dev/-/@ngneat/elf@v1.5.4-IR9D7yzwI1rfw1pX4eYX/dist=es2019,mode=types/lib/props-array-factory.d.ts:9:349

TS2614 [ERROR]: Module '"https://cdn.skypack.dev/error/unknown:rxjs?from=@ngneat/elf.js"' has no exported member 'OperatorFunction'. Did you mean to use 'import OperatorFunction from "https://cdn.skypack.dev/error/unknown:rxjs?from=@ngneat/elf.js"' instead?
import { OperatorFunction } from '/error/unknown:rxjs?from=@ngneat/elf';
         ~~~~~~~~~~~~~~~~
    at https://cdn.skypack.dev/-/@ngneat/elf@v1.5.4-IR9D7yzwI1rfw1pX4eYX/dist=es2019,mode=types/lib/props-factory.d.ts:1:10

TS2694 [ERROR]: Namespace '"https://cdn.skypack.dev/error/unknown:rxjs?from=@ngneat/elf.js"' has no exported member 'Observable'.
export declare const registry$: import("/error/unknown:rxjs?from=@ngneat/elf").Observable<{
                                                                               ~~~~~~~~~~
    at https://cdn.skypack.dev/-/@ngneat/elf@v1.5.4-IR9D7yzwI1rfw1pX4eYX/dist=es2019,mode=types/lib/registry.d.ts:2:80

TS2614 [ERROR]: Module '"https://cdn.skypack.dev/error/unknown:rxjs?from=@ngneat/elf.js"' has no exported member 'BehaviorSubject'. Did you mean to use 'import BehaviorSubject from "https://cdn.skypack.dev/error/unknown:rxjs?from=@ngneat/elf.js"' instead?
import { BehaviorSubject } from '/error/unknown:rxjs?from=@ngneat/elf';
         ~~~~~~~~~~~~~~~
    at https://cdn.skypack.dev/-/@ngneat/elf@v1.5.4-IR9D7yzwI1rfw1pX4eYX/dist=es2019,mode=types/lib/batch.d.ts:1:10

TS2694 [ERROR]: Namespace '"https://cdn.skypack.dev/error/unknown:rxjs?from=@ngneat/elf.js"' has no exported member 'Observable'.
export declare const batchDone$: import("/error/unknown:rxjs?from=@ngneat/elf").Observable<boolean>;
                                                                                ~~~~~~~~~~
    at https://cdn.skypack.dev/-/@ngneat/elf@v1.5.4-IR9D7yzwI1rfw1pX4eYX/dist=es2019,mode=types/lib/batch.d.ts:3:81

TS2614 [ERROR]: Module '"https://cdn.skypack.dev/error/unknown:rxjs?from=@ngneat/elf-persist-state.js"' has no exported member 'Observable'. Did you mean to use 'import Observable from "https://cdn.skypack.dev/error/unknown:rxjs?from=@ngneat/elf-persist-state.js"' instead?
import { Observable } from '/error/unknown:rxjs?from=@ngneat/elf-persist-state';
         ~~~~~~~~~~
    at https://cdn.skypack.dev/-/@ngneat/elf-persist-state@v1.1.1-SIpWzRwpHMNpKlYl0tw6/dist=es2019,mode=types/lib/storage.d.ts:1:10

TS2614 [ERROR]: Module '"https://cdn.skypack.dev/error/unknown:rxjs?from=@ngneat/elf-persist-state.js"' has no exported member 'Observable'. Did you mean to use 'import Observable from "https://cdn.skypack.dev/error/unknown:rxjs?from=@ngneat/elf-persist-state.js"' instead?
import { Observable } from '/error/unknown:rxjs?from=@ngneat/elf-persist-state';
         ~~~~~~~~~~
    at https://cdn.skypack.dev/-/@ngneat/elf-persist-state@v1.1.1-SIpWzRwpHMNpKlYl0tw6/dist=es2019,mode=types/lib/persist-state.d.ts:1:10

TS2614 [ERROR]: Module '"https://cdn.skypack.dev/error/unknown:@ngneat/elf?from=@ngneat/elf-persist-state.js"' has no exported member 'Store'. Did you mean to use 'import Store from "https://cdn.skypack.dev/error/unknown:@ngneat/elf?from=@ngneat/elf-persist-state.js"' instead?
import { Store, StoreValue } from '/error/unknown:@ngneat/elf?from=@ngneat/elf-persist-state';
         ~~~~~
    at https://cdn.skypack.dev/-/@ngneat/elf-persist-state@v1.1.1-SIpWzRwpHMNpKlYl0tw6/dist=es2019,mode=types/lib/persist-state.d.ts:3:10

TS2614 [ERROR]: Module '"https://cdn.skypack.dev/error/unknown:@ngneat/elf?from=@ngneat/elf-persist-state.js"' has no exported member 'StoreValue'. Did you mean to use 'import StoreValue from "https://cdn.skypack.dev/error/unknown:@ngneat/elf?from=@ngneat/elf-persist-state.js"' instead?
import { Store, StoreValue } from '/error/unknown:@ngneat/elf?from=@ngneat/elf-persist-state';
                ~~~~~~~~~~
    at https://cdn.skypack.dev/-/@ngneat/elf-persist-state@v1.1.1-SIpWzRwpHMNpKlYl0tw6/dist=es2019,mode=types/lib/persist-state.d.ts:3:17

TS2614 [ERROR]: Module '"https://cdn.skypack.dev/error/unknown:@ngneat/elf?from=@ngneat/elf-persist-state.js"' has no exported member 'Store'. Did you mean to use 'import Store from "https://cdn.skypack.dev/error/unknown:@ngneat/elf?from=@ngneat/elf-persist-state.js"' instead?
import { Store, StoreValue } from '/error/unknown:@ngneat/elf?from=@ngneat/elf-persist-state';
         ~~~~~
    at https://cdn.skypack.dev/-/@ngneat/elf-persist-state@v1.1.1-SIpWzRwpHMNpKlYl0tw6/dist=es2019,mode=types/lib/exclude-keys.d.ts:1:10

TS2614 [ERROR]: Module '"https://cdn.skypack.dev/error/unknown:@ngneat/elf?from=@ngneat/elf-persist-state.js"' has no exported member 'StoreValue'. Did you mean to use 'import StoreValue from "https://cdn.skypack.dev/error/unknown:@ngneat/elf?from=@ngneat/elf-persist-state.js"' instead?
import { Store, StoreValue } from '/error/unknown:@ngneat/elf?from=@ngneat/elf-persist-state';
                ~~~~~~~~~~
    at https://cdn.skypack.dev/-/@ngneat/elf-persist-state@v1.1.1-SIpWzRwpHMNpKlYl0tw6/dist=es2019,mode=types/lib/exclude-keys.d.ts:1:17

TS2614 [ERROR]: Module '"https://cdn.skypack.dev/error/unknown:rxjs?from=@ngneat/elf-persist-state.js"' has no exported member 'OperatorFunction'. Did you mean to use 'import OperatorFunction from "https://cdn.skypack.dev/error/unknown:rxjs?from=@ngneat/elf-persist-state.js"' instead?
import { OperatorFunction } from '/error/unknown:rxjs?from=@ngneat/elf-persist-state';
         ~~~~~~~~~~~~~~~~
    at https://cdn.skypack.dev/-/@ngneat/elf-persist-state@v1.1.1-SIpWzRwpHMNpKlYl0tw6/dist=es2019,mode=types/lib/exclude-keys.d.ts:2:10

Found 16 errors.
error: Failed at the start script
```

**Comment by bjesuiter** [comment]
It seems like it can't auto-resolve the rxjs import, can I do anything about this?
