### ISSUE TITLE
Package error for Knex

### ISSUE THREAD

**Issue by divmgl** [pikapkg/cdn#287]
Import map:

```
"knex": "https://cdn.skypack.dev/knex?dts"
```
```
error: Uncaught Error: Could not find module root given file: "https://cdn.esm.sh/v78/libpq@1.8.9/deno/libpq.js". Do you have a `package.json` file? 
    at Function.d.getRoot (https://cdn.esm.sh/v78/bindings@1.5.0/deno/bindings.js:4:616)
    at x (https://cdn.esm.sh/v78/bindings@1.5.0/deno/bindings.js:2:2388)
    at https://cdn.esm.sh/v78/libpq@1.8.9/deno/libpq.js:2:1264
    at https://cdn.esm.sh/v78/libpq@1.8.9/deno/libpq.js:2:913
    at https://cdn.esm.sh/v78/libpq@1.8.9/deno/libpq.js:2:4807
```

https://esm.sh/knex is also not working. Unsure what it could be.

**Comment by divmgl** [comment]
It looks like Knex uses a Node.js plugin, so this is a non-starter. Womp womp.
