### ISSUE TITLE
Skypack refers to "https://deno.land/std/node/fs.ts" that no longer exists

### ISSUE THREAD

**Issue by noam-honig** [pikapkg/cdn#342]
I have some code that originally refers to node's "fs" library.

Sky pack replaces the import to "https://deno.land/std/node/fs.ts" and that doesn't exist any more in version 178 of deno since it was moved to deno's core - as mentioned in [178 release notes](https://github.com/denoland/deno_std/releases/tag/0.178.0)

This causes the following error on my deno project:
error: TypeError: Module not found "https://deno.land/std/node/fs.ts".
    at https://cdn.skypack.dev/-/remult@v0.18.0-IpczTvqeMpYibVQi1UiX/dist=es2019,mode=imports/optimized/common/JsonEntityFileStorage-67f13780.js:1:66
    at async https://cdn.skypack.dev/-/remult@v0.18.0-IpczTvqeMpYibVQi1UiX/dist=es2019,mode=imports/optimized/common/expressBridge-1b8a9a35.js:14:17

Here's the code generated by SkyPack:
https://cdn.skypack.dev/-/remult@v0.18.0-IpczTvqeMpYibVQi1UiX/dist=es2019,mode=imports/optimized/common/JsonEntityFileStorage-67f13780.js

And here is the original code:
https://github.com/remult/remult/blob/master/projects/core/server/JsonEntityFileStorage.ts

**Comment by sprutner** [comment]
I also have this issue
