### ISSUE TITLE
Types not working in some packages (Deno)

### ISSUE THREAD

**Issue by Soremwar** [pikapkg/cdn#42]
Try importing from the example from your website

```javascript
import React from "https://cdn.skypack.dev/react?dts";

console.log(React)
```

Will result in the following:
```log
# deno run test.ts
error: relative import path "global.d.ts" not prefixed with / or ./ or ../ Imported from "https://cdn.skypack.dev/-/react@v16.13.1-zjOHmKoBShdi3wIQWY2z/dist=es2020,mode=types/index.d.ts"
```

Importing without types works well

**Comment by drwpow** [comment]
Hey @Soremwar! We’ve shipped some updates to the CDN and I’m no longer seeing the behavior you described in Deno. Can you confirm? (Note: omit the `?dts` at the end—Deno should handle that automatically for you)

**Comment by Soremwar** [comment]
Hi @drwpow, as it turns out it isn't working yet. Deno doesn't seem to be picking any types from the React import in Skypack when `?dts` is not included

**Comment by drwpow** [comment]
Sorry—forgot to check back in! You were indeed correct; Deno does need `?dts` to perform typechecking; my mistake. We‘ve made a change here; can you confirm it‘s working on your end now?

**Comment by Soremwar** [comment]
At first glance it would seem so, VSCode is finally giving me autocompletion, however when compiling a file such as `mod.tsx` with a simple program like the following
```jsx
import React from "https://cdn.skypack.dev/react?dts";

const x = () => {
  return (
    <h1>abcd</h1>
  );
};

export default x;
```
You get this:
```log
error: TS2694 [ERROR]: Namespace '"https://cdn.skypack.dev/error/unknown:csstype?from=react"' has no exported member 'Properties'.
    export interface CSSProperties extends CSS.Properties<string | number> {
                                               ~~~~~~~~~~
    at https://cdn.skypack.dev/-/react@v17.0.1-POc2QItJkO3bjziOktDB/dist=es2020,mode=types/index.d.ts:1546:48

TS2694 [ERROR]: Namespace '"https://cdn.skypack.dev/error/unknown:prop-types?from=react"' has no exported member 'Validator'.
    type Validator<T> = PropTypes.Validator<T>;
                                  ~~~~~~~~~
    at https://cdn.skypack.dev/-/react@v17.0.1-POc2QItJkO3bjziOktDB/dist=es2020,mode=types/index.d.ts:2843:35

TS2694 [ERROR]: Namespace '"https://cdn.skypack.dev/error/unknown:prop-types?from=react"' has no exported member 'Requireable'.
    type Requireable<T> = PropTypes.Requireable<T>;
                                    ~~~~~~~~~~~
    at https://cdn.skypack.dev/-/react@v17.0.1-POc2QItJkO3bjziOktDB/dist=es2020,mode=types/index.d.ts:2845:37

TS2694 [ERROR]: Namespace '"https://cdn.skypack.dev/error/unknown:prop-types?from=react"' has no exported member 'ValidationMap'.
    type ValidationMap<T> = PropTypes.ValidationMap<T>;
                                      ~~~~~~~~~~~~~
    at https://cdn.skypack.dev/-/react@v17.0.1-POc2QItJkO3bjziOktDB/dist=es2020,mode=types/index.d.ts:2847:39

TS2339 [ERROR]: Property 'any' does not exist on type 'typeof import("https://cdn.skypack.dev/error/unknown:prop-types?from=react")'.
        any: typeof PropTypes.any;
                              ~~~
    at https://cdn.skypack.dev/-/react@v17.0.1-POc2QItJkO3bjziOktDB/dist=es2020,mode=types/index.d.ts:2858:31

TS2339 [ERROR]: Property 'array' does not exist on type 'typeof import("https://cdn.skypack.dev/error/unknown:prop-types?from=react")'.
        array: typeof PropTypes.array;
                                ~~~~~
    at https://cdn.skypack.dev/-/react@v17.0.1-POc2QItJkO3bjziOktDB/dist=es2020,mode=types/index.d.ts:2859:33

TS2339 [ERROR]: Property 'bool' does not exist on type 'typeof import("https://cdn.skypack.dev/error/unknown:prop-types?from=react")'.
        bool: typeof PropTypes.bool;
                               ~~~~
    at https://cdn.skypack.dev/-/react@v17.0.1-POc2QItJkO3bjziOktDB/dist=es2020,mode=types/index.d.ts:2860:32

TS2339 [ERROR]: Property 'func' does not exist on type 'typeof import("https://cdn.skypack.dev/error/unknown:prop-types?from=react")'.
        func: typeof PropTypes.func;
                               ~~~~
    at https://cdn.skypack.dev/-/react@v17.0.1-POc2QItJkO3bjziOktDB/dist=es2020,mode=types/index.d.ts:2861:32

TS2339 [ERROR]: Property 'number' does not exist on type 'typeof import("https://cdn.skypack.dev/error/unknown:prop-types?from=react")'.
        number: typeof PropTypes.number;
                                 ~~~~~~
    at https://cdn.skypack.dev/-/react@v17.0.1-POc2QItJkO3bjziOktDB/dist=es2020,mode=types/index.d.ts:2862:34

TS2339 [ERROR]: Property 'object' does not exist on type 'typeof import("https://cdn.skypack.dev/error/unknown:prop-types?from=react")'.
        object: typeof PropTypes.object;
                                 ~~~~~~
    at https://cdn.skypack.dev/-/react@v17.0.1-POc2QItJkO3bjziOktDB/dist=es2020,mode=types/index.d.ts:2863:34

TS2339 [ERROR]: Property 'string' does not exist on type 'typeof import("https://cdn.skypack.dev/error/unknown:prop-types?from=react")'.
        string: typeof PropTypes.string;
                                 ~~~~~~
    at https://cdn.skypack.dev/-/react@v17.0.1-POc2QItJkO3bjziOktDB/dist=es2020,mode=types/index.d.ts:2864:34

TS2339 [ERROR]: Property 'node' does not exist on type 'typeof import("https://cdn.skypack.dev/error/unknown:prop-types?from=react")'.
        node: typeof PropTypes.node;
                               ~~~~
    at https://cdn.skypack.dev/-/react@v17.0.1-POc2QItJkO3bjziOktDB/dist=es2020,mode=types/index.d.ts:2865:32

TS2339 [ERROR]: Property 'element' does not exist on type 'typeof import("https://cdn.skypack.dev/error/unknown:prop-types?from=react")'.
        element: typeof PropTypes.element;
                                  ~~~~~~~
    at https://cdn.skypack.dev/-/react@v17.0.1-POc2QItJkO3bjziOktDB/dist=es2020,mode=types/index.d.ts:2866:35

TS2339 [ERROR]: Property 'instanceOf' does not exist on type 'typeof import("https://cdn.skypack.dev/error/unknown:prop-types?from=react")'.
        instanceOf: typeof PropTypes.instanceOf;
                                     ~~~~~~~~~~
    at https://cdn.skypack.dev/-/react@v17.0.1-POc2QItJkO3bjziOktDB/dist=es2020,mode=types/index.d.ts:2867:38

TS2339 [ERROR]: Property 'oneOf' does not exist on type 'typeof import("https://cdn.skypack.dev/error/unknown:prop-types?from=react")'.
        oneOf: typeof PropTypes.oneOf;
                                ~~~~~
    at https://cdn.skypack.dev/-/react@v17.0.1-POc2QItJkO3bjziOktDB/dist=es2020,mode=types/index.d.ts:2868:33

TS2339 [ERROR]: Property 'oneOfType' does not exist on type 'typeof import("https://cdn.skypack.dev/error/unknown:prop-types?from=react")'.
        oneOfType: typeof PropTypes.oneOfType;
                                    ~~~~~~~~~
    at https://cdn.skypack.dev/-/react@v17.0.1-POc2QItJkO3bjziOktDB/dist=es2020,mode=types/index.d.ts:2869:37

TS2339 [ERROR]: Property 'arrayOf' does not exist on type 'typeof import("https://cdn.skypack.dev/error/unknown:prop-types?from=react")'.
        arrayOf: typeof PropTypes.arrayOf;
                                  ~~~~~~~
    at https://cdn.skypack.dev/-/react@v17.0.1-POc2QItJkO3bjziOktDB/dist=es2020,mode=types/index.d.ts:2870:35

TS2339 [ERROR]: Property 'objectOf' does not exist on type 'typeof import("https://cdn.skypack.dev/error/unknown:prop-types?from=react")'.
        objectOf: typeof PropTypes.objectOf;
                                   ~~~~~~~~
    at https://cdn.skypack.dev/-/react@v17.0.1-POc2QItJkO3bjziOktDB/dist=es2020,mode=types/index.d.ts:2871:36

TS2339 [ERROR]: Property 'shape' does not exist on type 'typeof import("https://cdn.skypack.dev/error/unknown:prop-types?from=react")'.
        shape: typeof PropTypes.shape;
                                ~~~~~
    at https://cdn.skypack.dev/-/react@v17.0.1-POc2QItJkO3bjziOktDB/dist=es2020,mode=types/index.d.ts:2872:33

TS2339 [ERROR]: Property 'exact' does not exist on type 'typeof import("https://cdn.skypack.dev/error/unknown:prop-types?from=react")'.
        exact: typeof PropTypes.exact;
                                ~~~~~
    at https://cdn.skypack.dev/-/react@v17.0.1-POc2QItJkO3bjziOktDB/dist=es2020,mode=types/index.d.ts:2873:33

TS2694 [ERROR]: Namespace '"https://cdn.skypack.dev/error/unknown:prop-types?from=react"' has no exported member 'InferProps'.
    ? Defaultize<MergePropTypes<P, PropTypes.InferProps<T>>, D>
                                             ~~~~~~~~~~
    at https://cdn.skypack.dev/-/react@v17.0.1-POc2QItJkO3bjziOktDB/dist=es2020,mode=types/index.d.ts:2963:46

TS2694 [ERROR]: Namespace '"https://cdn.skypack.dev/error/unknown:prop-types?from=react"' has no exported member 'InferProps'.
        ? MergePropTypes<P, PropTypes.InferProps<T>>
                                      ~~~~~~~~~~
    at https://cdn.skypack.dev/-/react@v17.0.1-POc2QItJkO3bjziOktDB/dist=es2020,mode=types/index.d.ts:2965:39

Found 22 errors.
```
This issues all seem to be from other libraries such as PropTypes which React uses internally. Probably this libraries aren't getting correctly processed

There is some advancement, but it doesn't seem like types are getting transpiled right quite yet

**Comment by drwpow** [comment]
Thanks for checking. I think this is related to #65—when generating types it seems like we don’t have everything needed in-scope, thus yielding the missing type references. We probably need to install more dependencies. Will investigate further.

**Comment by FredKSchott** [comment]
Yup, I think I've found the error. It occurs when `@types/react` relies on its own dependencies that are different from the main `react` package. Will get this fixed asap since we really should have React + Deno support working.

**Comment by drwpow** [comment]
Update: we’ve shipped a few updates to Deno types to improve support. I believe this issue should be resolved if you `--reload` from Deno, but please comment or reopen if you encounter any issues.
