### ISSUE TITLE
import lodash with Deno with 502 Bad Gateway

### ISSUE THREAD

**Issue by axetroy** [pikapkg/cdn#65]
```ts
import { sortBy } from "https://cdn.skypack.dev/lodash?dts";
```

```
Download https://cdn.skypack.dev/-/lodash@v4.17.20-xzUf7QX4Ab65fkc5HuZp/dist=es2020,mode=types/common/number.d.ts
Download https://cdn.skypack.dev/-/lodash@v4.17.20-xzUf7QX4Ab65fkc5HuZp/dist=es2020,mode=types/common/seq.d.ts
Download https://cdn.skypack.dev/-/lodash@v4.17.20-xzUf7QX4Ab65fkc5HuZp/dist=es2020,mode=types/common/string.d.ts
Download https://cdn.skypack.dev/-/lodash@v4.17.20-xzUf7QX4Ab65fkc5HuZp/dist=es2020,mode=types/common/util.d.ts
Download https://cdn.skypack.dev/-/lodash@v4.17.20-xzUf7QX4Ab65fkc5HuZp/dist=es2020,mode=types/common/object.d.ts
Download https://cdn.skypack.dev/-/lodash@v4.17.20-xzUf7QX4Ab65fkc5HuZp/dist=es2020,mode=types/common/common.d.ts
Download https://cdn.skypack.dev/-/lodash@v4.17.20-xzUf7QX4Ab65fkc5HuZp/dist=es2020,mode=types/common/math.d.ts
Download https://cdn.skypack.dev/-/lodash@v4.17.20-xzUf7QX4Ab65fkc5HuZp/dist=es2020,mode=types/common/date.d.ts
Download https://cdn.skypack.dev/-/lodash@v4.17.20-xzUf7QX4Ab65fkc5HuZp/dist=es2020,mode=types/common/lang.d.ts
Download https://cdn.skypack.dev/-/lodash@v4.17.20-xzUf7QX4Ab65fkc5HuZp/dist=es2020,mode=types/common/function.d.ts
Download https://cdn.skypack.dev/-/lodash@v4.17.20-xzUf7QX4Ab65fkc5HuZp/dist=es2020,mode=types/common/collection.d.ts
Download https://cdn.skypack.dev/-/lodash@v4.17.20-xzUf7QX4Ab65fkc5HuZp/dist=es2020,mode=types/common/array.d.ts
error: Import 'https://cdn.skypack.dev/-/lodash@v4.17.20-xzUf7QX4Ab65fkc5HuZp/dist=es2020,mode=types/common/string.d.ts' failed: 502 Bad Gateway
    at https://cdn.skypack.dev/-/lodash@v4.17.20-xzUf7QX4Ab65fkc5HuZp/dist=es2020,mode=types/index.d.ts:25:0
```

**Comment by drwpow** [comment]
Thanks for reporting! I believe this is related to #59, which we‘re still investigating

**Comment by FredKSchott** [comment]
Update: our ESM parser has trouble with this line of DTS code: `import _ = require("../index");`

But even with that fixed, I see some strange DTS errors:
```
TS2304 [ERROR]: Cannot find name 'Many'.
        overEvery<TArgs>(...iteratees: Array<Many<(...args: TArgs[]) => boolean>>): Function<(...args: Parameters<T> | TArgs[]) => boolean>;
                                             ~~~~
    at https://cdn.skypack.dev/-/lodash@v4.17.20-AK8bV2imBhL91nXpBIDu/dist=es2020,mode=types/common/util.d.ts:771:46

TS2304 [ERROR]: Cannot find name 'Many'.
        overEvery<TArgs>(...iteratees: Array<Many<(...args: TArgs[]) => boolean>>): FunctionChain<(...args:  TArgs[]) => boolean>;
                                             ~~~~
    at https://cdn.skypack.dev/-/lodash@v4.17.20-AK8bV2imBhL91nXpBIDu/dist=es2020,mode=types/common/util.d.ts:777:46


...
```

I'm not actually sure why this is, but it seems to be either a Deno issue, an outdated types issue, or both.

**Comment by somethingelseentirely** [comment]
I encounter a similar error when importing `aws-sdk` on deno.

```javascript
import AWS from 'https://cdn.skypack.dev/aws-sdk';
```

leads to
```
Download https://cdn.skypack.dev/new/aws-sdk@v2.812.0/dist=es2020
Download https://cdn.skypack.dev/-/aws-sdk@v2.812.0-8mAlFG0YaTLEtBLYaUlm/dist=es2020/aws-sdk.js
error: Import 'https://cdn.skypack.dev/-/aws-sdk@v2.812.0-8mAlFG0YaTLEtBLYaUlm/dist=es2020/aws-sdk.js' failed: 502 Bad Gateway
    at https://cdn.skypack.dev/aws-sdk:15:0
```

**Comment by drwpow** [comment]
Update: we’ve significantly improved the `?dts` handling for Deno. You should be able to load many more packages now than you could before.

But for `lodash` specifically, we don’t support the `require()` statement that their current type definitions rely on. That needs to be updated to modern TypeScript syntax for it to work.

For `aws-sdk`, that package isn’t currently loadable from Skypack as it’s meant to run in a Node environment. We’d recommend using that in Node.js for now.
